### ISSUE TITLE
Log of background workers

### ISSUE THREAD

**Issue by darold** [gleu/pg_log_userqueries#10]
When `pg_log_userqueries.log_superusers = on` the extension log queries executed by bgworkers like powa with a trace like:
```
2017-12-20 09:19:13 CET [5956]: [4098802-1] user=,db=,client= LOG:  USERQUERIES SELECT powa_take_snapshot()
```
I guess that pg_log_userqueries might not log queries when the user or db is not set.

**Comment by gleu** [comment]
I just added a fix to only log when username and database name are set. Thanks for the report.
