### ISSUE TITLE
Add a mecanism to filter with more detail.

### ISSUE THREAD

**Issue by blogh** [gleu/pg_log_userqueries#15]
The current version allows to filter queries by, for example, username.
It might be useful to filter using negations, in this case since users can be added to the database at anytime.
Updating the filter each time is cumbersome and error prone.

A second argument is that, regex.h doesn't support look ahead / look behind. 
The only way is to use this kind of horror : "^\([^m]\)\|\(m[^a]\)\|\(ma[^c]\)" to filter out "mac".

**Comment by gleu** [comment]
PR is interesting. Needs some work to make it work though.

**Comment by gleu** [comment]
PR #16 has been merged. Thanks a lot.
