### ISSUE TITLE
There's no .control file

### ISSUE THREAD

**Issue by yhuelf** [gleu/pg_log_userqueries#20]

**Comment by gleu** [comment]
And for a good reason, which is it doesn't need one. It isn't an extension, there's no SQL script to execute on a database. As an example, see auto_explain. No SQL script, no control file.

**Comment by yhuelf** [comment]
OK :-)

I should have stated my initial problem instead. Is there a way to get the version of this module?

**Comment by gleu** [comment]
Right now, no, there's no way (except if the installed packet has a version number).

I've just commited a patch to allow checking the lib version. It could be done this way:

```
$ strings pg_log_userqueries.o | grep "pg_log_userqueries version"
pg_log_userqueries version 1.2
```

**Comment by yhuelf** [comment]
It works for me. Thanks!

**Comment by gleu** [comment]
OK, then, I'm gonna release a new version with both fixes. Thanks again!
