### ISSUE TITLE
pg_log_userqueries.c:741: warning : implicit declaration of function ‘time’

### ISSUE THREAD

**Issue by darold** [gleu/pg_log_userqueries#6]
You might need to add the following line at top of pg_log_userqueries.c

    #include <time.h>

Regards

**Comment by gleu** [comment]
Works without it on my laptop. What issue do you have?

**Comment by darold** [comment]
This is just a warning at compile time on a RHELrelease 6.5:
```
pg_log_userqueries.c: In function ‘check_time_switch’:
pg_log_userqueries.c:741: warning : implicit declaration of function ‘time’
```

**Comment by gleu** [comment]
OK. Adding it doesn't cause any issue here, and if it fixes a warning, then I'm all for it.

Pushed on ffccc79e589270e9db09eb0178fee7a9dcc873c8

**Comment by gleu** [comment]
Thanks.
